---
title: "ESM 244 Assignment 1 Part 1"
author: "Aaron Kreisberg"
date: "1/20/2021"
output: html_document
---

```{r setup, include=FALSE, message=FALSE, warning=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(janitor)
library(here)
library(readxl)
library(lubridate)
library(patchwork)
```


```{r, message=FALSE, warning=FALSE}
sierra_amphibians <- read_excel(here("data", "sierra_amphibians.xlsx"))

sierra_ramu <- sierra_amphibians %>% 
  select("survey_date", "amphibian_species", "amphibian_life_stage", "amphibian_number") %>% 
  filter(amphibian_species == "RAMU") %>% 
  drop_na() %>% 
  filter(amphibian_life_stage %in% c("Adult", "SubAdult", "Tadpole")) %>%
  mutate(date = ymd(survey_date)) %>% 
  mutate(year = year(date)) %>% 
  group_by(year, amphibian_life_stage) %>% 
  summarise(amphibian_number = sum(amphibian_number)) 


  
ramu_count <- ggplot(data = sierra_ramu, aes(x = year, y = amphibian_number)) +
  geom_point(aes(color = "amphibian_life_stage")) + 
  geom_line(na.translate = FALSE) +
  facet_wrap(~amphibian_life_stage, scales = "free_y") +
  labs(x = "Year",
       y = "Amphibian Count") +
  theme(legend.position = "none")
   
 
```



```{r, message=FALSE, warning=FALSE}
sierra_lakes <- read_excel(here("data", "sierra_amphibians.xlsx")) %>% 
  select("lake_id", "amphibian_species", "amphibian_life_stage", "amphibian_number") %>% 
  filter(amphibian_species == "RAMU") %>% 
  filter(amphibian_life_stage %in% c("Adult", "SubAdult")) %>% 
  add_column(lake = "Lake") %>% 
  unite(lake_id, c(lake, lake_id), sep = "_") %>% 
  group_by(lake_id) %>% 
  summarise(amphibian_number = sum(amphibian_number)) 
  
  
top_5_lakes <- sierra_lakes %>% 
  slice_max(amphibian_number, n = 5) 

```

```{r, message=FALSE, warning=FALSE}

top_5_bargraph <- ggplot(data = top_5_lakes, aes(x = lake_id, y = amphibian_number)) +
  geom_bar(stat =  "identity")

```



```{r}
ramu_count / top_5_bargraph
```


**Figure 1:** 

Citation: Knapp, R.A., C. Pavelka, E.E. Hegeman, and T.C. Smith. 2020. The Sierra Lakes Inventory Project: Non-Native fish and community composition of lakes and ponds in the Sierra Nevada, California ver 2. Environmental Data Initiative. https://doi.org/10.6073/pasta/d835832d7fd00d9e4466e44eea87fab3 (Accessed 2021-01-25).
